server:
  port: 8081
grpc:
  server:
    port: 9090

spring:
  profiles:
    active: postgres
  sql:
    init:
      enabled: true

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false